(cl:defpackage efficiency-srv
  (:use )
  (:export
   "EFFICIENCY_S"
   "<EFFICIENCY_S-REQUEST>"
   "EFFICIENCY_S-REQUEST"
   "<EFFICIENCY_S-RESPONSE>"
   "EFFICIENCY_S-RESPONSE"
   "EFFICIENCY_S2"
   "<EFFICIENCY_S2-REQUEST>"
   "EFFICIENCY_S2-REQUEST"
   "<EFFICIENCY_S2-RESPONSE>"
   "EFFICIENCY_S2-RESPONSE"
  ))

