/* Auto-generated by genmsg_cpp for file /home/mfcarmona/ros/isis/efficiency/srv/Efficiency_s2.srv */
#ifndef EFFICIENCY_SERVICE_EFFICIENCY_S2_H
#define EFFICIENCY_SERVICE_EFFICIENCY_S2_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"

#include "geometry_msgs/Point.h"
#include "nav_msgs/Odometry.h"
#include "nav_msgs/GridCells.h"
#include "geometry_msgs/Pose2D.h"


#include "efficiency/Efficiency_m.h"

namespace efficiency
{
template <class ContainerAllocator>
struct Efficiency_s2Request_ : public ros::Message
{
  typedef Efficiency_s2Request_<ContainerAllocator> Type;

  Efficiency_s2Request_()
  : comand()
  , robotPos()
  , obstacles()
  , target()
  {
  }

  Efficiency_s2Request_(const ContainerAllocator& _alloc)
  : comand(_alloc)
  , robotPos(_alloc)
  , obstacles(_alloc)
  , target(_alloc)
  {
  }

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _comand_type;
   ::geometry_msgs::Point_<ContainerAllocator>  comand;

  typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _robotPos_type;
   ::nav_msgs::Odometry_<ContainerAllocator>  robotPos;

  typedef  ::nav_msgs::GridCells_<ContainerAllocator>  _obstacles_type;
   ::nav_msgs::GridCells_<ContainerAllocator>  obstacles;

  typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _target_type;
   ::geometry_msgs::Pose2D_<ContainerAllocator>  target;


private:
  static const char* __s_getDataType_() { return "efficiency/Efficiency_s2Request"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0f8e727d89550db30353a4d527677da4"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "803581245f4fa5ea991fd5cd635af433"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "geometry_msgs/Point comand\n\
nav_msgs/Odometry robotPos\n\
nav_msgs/GridCells obstacles\n\
geometry_msgs/Pose2D target\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertianty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: nav_msgs/GridCells\n\
#an array of cells in a 2D grid\n\
Header header\n\
float32 cell_width\n\
float32 cell_height\n\
geometry_msgs/Point[] cells\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, comand);
    ros::serialization::serialize(stream, robotPos);
    ros::serialization::serialize(stream, obstacles);
    ros::serialization::serialize(stream, target);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, comand);
    ros::serialization::deserialize(stream, robotPos);
    ros::serialization::deserialize(stream, obstacles);
    ros::serialization::deserialize(stream, target);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(comand);
    size += ros::serialization::serializationLength(robotPos);
    size += ros::serialization::serializationLength(obstacles);
    size += ros::serialization::serializationLength(target);
    return size;
  }

  typedef boost::shared_ptr< ::efficiency::Efficiency_s2Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::efficiency::Efficiency_s2Request_<ContainerAllocator>  const> ConstPtr;
}; // struct Efficiency_s2Request
typedef  ::efficiency::Efficiency_s2Request_<std::allocator<void> > Efficiency_s2Request;

typedef boost::shared_ptr< ::efficiency::Efficiency_s2Request> Efficiency_s2RequestPtr;
typedef boost::shared_ptr< ::efficiency::Efficiency_s2Request const> Efficiency_s2RequestConstPtr;


template <class ContainerAllocator>
struct Efficiency_s2Response_ : public ros::Message
{
  typedef Efficiency_s2Response_<ContainerAllocator> Type;

  Efficiency_s2Response_()
  : eta()
  {
  }

  Efficiency_s2Response_(const ContainerAllocator& _alloc)
  : eta(_alloc)
  {
  }

  typedef  ::efficiency::Efficiency_m_<ContainerAllocator>  _eta_type;
   ::efficiency::Efficiency_m_<ContainerAllocator>  eta;


private:
  static const char* __s_getDataType_() { return "efficiency/Efficiency_s2Response"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5e6f934f07b7f4fd2e0fe69b58994708"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "803581245f4fa5ea991fd5cd635af433"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Efficiency_m eta\n\
\n\
\n\
\n\
================================================================================\n\
MSG: efficiency/Efficiency_m\n\
float32 Global\n\
float32 Safety\n\
float32 Directness\n\
float32 Smoothness\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, eta);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, eta);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(eta);
    return size;
  }

  typedef boost::shared_ptr< ::efficiency::Efficiency_s2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::efficiency::Efficiency_s2Response_<ContainerAllocator>  const> ConstPtr;
}; // struct Efficiency_s2Response
typedef  ::efficiency::Efficiency_s2Response_<std::allocator<void> > Efficiency_s2Response;

typedef boost::shared_ptr< ::efficiency::Efficiency_s2Response> Efficiency_s2ResponsePtr;
typedef boost::shared_ptr< ::efficiency::Efficiency_s2Response const> Efficiency_s2ResponseConstPtr;

struct Efficiency_s2
{

typedef Efficiency_s2Request Request;
typedef Efficiency_s2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Efficiency_s2
} // namespace efficiency

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::efficiency::Efficiency_s2Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0f8e727d89550db30353a4d527677da4";
  }

  static const char* value(const  ::efficiency::Efficiency_s2Request_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0f8e727d89550db3ULL;
  static const uint64_t static_value2 = 0x0353a4d527677da4ULL;
};

template<class ContainerAllocator>
struct DataType< ::efficiency::Efficiency_s2Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "efficiency/Efficiency_s2Request";
  }

  static const char* value(const  ::efficiency::Efficiency_s2Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::efficiency::Efficiency_s2Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Point comand\n\
nav_msgs/Odometry robotPos\n\
nav_msgs/GridCells obstacles\n\
geometry_msgs/Pose2D target\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertianty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: nav_msgs/GridCells\n\
#an array of cells in a 2D grid\n\
Header header\n\
float32 cell_width\n\
float32 cell_height\n\
geometry_msgs/Point[] cells\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const  ::efficiency::Efficiency_s2Request_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::efficiency::Efficiency_s2Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5e6f934f07b7f4fd2e0fe69b58994708";
  }

  static const char* value(const  ::efficiency::Efficiency_s2Response_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5e6f934f07b7f4fdULL;
  static const uint64_t static_value2 = 0x2e0fe69b58994708ULL;
};

template<class ContainerAllocator>
struct DataType< ::efficiency::Efficiency_s2Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "efficiency/Efficiency_s2Response";
  }

  static const char* value(const  ::efficiency::Efficiency_s2Response_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::efficiency::Efficiency_s2Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Efficiency_m eta\n\
\n\
\n\
\n\
================================================================================\n\
MSG: efficiency/Efficiency_m\n\
float32 Global\n\
float32 Safety\n\
float32 Directness\n\
float32 Smoothness\n\
\n\
\n\
";
  }

  static const char* value(const  ::efficiency::Efficiency_s2Response_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::efficiency::Efficiency_s2Response_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::efficiency::Efficiency_s2Request_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.comand);
    stream.next(m.robotPos);
    stream.next(m.obstacles);
    stream.next(m.target);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Efficiency_s2Request_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::efficiency::Efficiency_s2Response_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.eta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Efficiency_s2Response_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<efficiency::Efficiency_s2> {
  static const char* value() 
  {
    return "803581245f4fa5ea991fd5cd635af433";
  }

  static const char* value(const efficiency::Efficiency_s2&) { return value(); } 
};

template<>
struct DataType<efficiency::Efficiency_s2> {
  static const char* value() 
  {
    return "efficiency/Efficiency_s2";
  }

  static const char* value(const efficiency::Efficiency_s2&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<efficiency::Efficiency_s2Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "803581245f4fa5ea991fd5cd635af433";
  }

  static const char* value(const efficiency::Efficiency_s2Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<efficiency::Efficiency_s2Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "efficiency/Efficiency_s2";
  }

  static const char* value(const efficiency::Efficiency_s2Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<efficiency::Efficiency_s2Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "803581245f4fa5ea991fd5cd635af433";
  }

  static const char* value(const efficiency::Efficiency_s2Response_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<efficiency::Efficiency_s2Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "efficiency/Efficiency_s2";
  }

  static const char* value(const efficiency::Efficiency_s2Response_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // EFFICIENCY_SERVICE_EFFICIENCY_S2_H

