(cl:defpackage collaborative_control-srv
  (:use )
  (:export
   "COLLABORATIVE_CONTROL_S"
   "<COLLABORATIVE_CONTROL_S-REQUEST>"
   "COLLABORATIVE_CONTROL_S-REQUEST"
   "<COLLABORATIVE_CONTROL_S-RESPONSE>"
   "COLLABORATIVE_CONTROL_S-RESPONSE"
  ))

